Repository ao-libre/finisterra, pull requests merged in 2019-07, with the labels that each got.

#131 Update spells.json
  shared/resources/spells/spells.json
Labels: enhancement

#145 non-static GUI
  client/src/game/managers/AOInputProcessor.java
  client/src/game/network/GameNotificationProcessor.java
  client/src/game/screens/GameScreen.java
  client/src/game/systems/render/world/TargetRenderingSystem.java
  client/src/game/ui/GUI.java
  client/src/game/ui/SpellView.java
Labels: bug

#149 game.toLogin() as runnable
  client/src/game/systems/network/ClientSystem.java
Labels: bug

#151 Update Gdd
  docs/gdd.md
  docs/ideas-desarollo.md
Labels: documentation

#164 Create Readme.md
  design/readme.md
Labels: Design Center APP, documentation

#167 Globally access client configuration settings by injection.
  client/src/game/AOGame.java
  client/src/game/ClientConfiguration.java
  client/src/game/screens/GameScreen.java
  desktop/src/launcher/DesktopLauncher.java
Labels: enhancement
