Repository ao-libre/finisterra, pull requests merged in 2019-11, with the labels that each got.

#200 adds messages for roomscreen using shared/resources/lang
  client/src/game/screens/RoomScreen.java
  shared/resources/lang/messages_en_US.properties
  shared/resources/lang/messages_es_AR.properties
  shared/resources/lang/messages_es_US.properties
  shared/src/shared/util/Messages.java
Labels: help wanted

#216 Agregamos servidor NewYork
  desktop/Config.json
Labels: enhancement

#219 Adding room limit creation by server configuration
  client/src/game/network/ClientResponseProcessor.java
  client/src/game/screens/LobbyScreen.java
  client/src/game/screens/LoginScreen.java
  server/Server.json
  server/src/server/ServerConfiguration.java
  server/src/server/core/Finisterra.java
  server/src/server/network/FinisterraRequestProcessor.java
  shared/resources/lang/messages_en_US.properties
  shared/resources/lang/messages_es_AR.properties
  shared/resources/lang/messages_es_US.properties
  shared/src/shared/model/lobby/Lobby.java
  shared/src/shared/network/init/NetworkDictionary.java
  shared/src/shared/network/lobby/CreateRoomResponse.java
  shared/src/shared/util/Messages.java
Labels: enhancement

#193 Fix & refactor JPackage app bundling procedure.
  .gitignore
  build.gradle
  desktop/build.gradle
  gradle.properties
  server/build.gradle
Labels: enhancement

#225 Fix commit 176e631
  .github/FUNDING.yml
  .travis.yml
  client/src/game/ui/user/UserImage.java
Labels: bug

#214 Implementa combate con arcos y activa el personaje arquero
  client/src/game/managers/AOInputProcessor.java
  client/src/game/ui/Inventory.java
  server/src/server/core/Server.java
  server/src/server/network/ServerRequestProcessor.java
  server/src/server/systems/EntityFactorySystem.java
  server/src/server/systems/combat/RangedCombatSystem.java
  shared/resources/lang/messages_en_US.properties
  shared/resources/lang/messages_es_AR.properties
  shared/resources/lang/messages_es_US.properties
  shared/resources/objects/weapon.json
  shared/src/shared/interfaces/Hero.java
  shared/src/shared/model/AttackType.java
  shared/src/shared/network/combat/AttackRequest.java
  shared/src/shared/objects/types/WeaponKind.java
  shared/src/shared/objects/types/WeaponObj.java
  shared/src/shared/util/Messages.java
Labels: enhancement

#230 Agregamos template-Issue para reportar errores en la docu
  .github/ISSUE_TEMPLATE/docu-report.md
Labels: documentation

#237 Fix some unchecked expressions using diamond operator.
  client/src/game/loaders/ImageLoader.java
  client/src/game/screens/transitions/FadingGame.java
  client/src/game/screens/transitions/SlicingTransition.java
  client/src/game/ui/SpellSlot.java
  client/src/game/ui/SpellSlotEC.java
  shared/src/shared/map/AutoTiler.java
  shared/src/shared/model/loaders/NPCLoader.java
  shared/src/shared/model/npcs/NPC.java
Labels: bug

#240 fix usar energía al disparar flechas
  server/src/server/systems/combat/RangedCombatSystem.java
Labels: enhancement

#241 [Documentación] Creamos una basada en zim-wiki
  docs/get-started/development-environment.md
  docs/get-started/run-on-console.md
  docs/get-started/workflow-github.md
  docs/index.txt
  docs/index/Español.txt
  docs/index/Español/ChangeLog.txt
  docs/index/Español/Comenzar.txt
  docs/index/Español/Comenzar/1_Compilar_para_probar_o_testear.txt
  docs/index/Español/Comenzar/2_Montar_el_entorno_de_desarrollo.txt
  docs/index/Español/Comenzar/3_Montar_un_Servidor.txt
  docs/index/Español/Comenzar/4_Realizar_un_aporte.txt
  docs/index/Español/Comenzar/4_Realizar_un_aporte/Flujo_de_trabajo_en_Github.txt
  docs/index/Español/Comenzar/4_Realizar_un_aporte/Flujo_de_trabajo_en_Github/Componer_una_Pull_Request.txt
  docs/index/Español/Comenzar/Editar_esta_wiki.txt
  docs/index/Español/Código_Fuente.txt
  docs/index/Español/Código_Fuente/Dependencias.txt
  docs/index/Español/Código_Fuente/Implementando_Sonido.txt
  docs/index/Español/Código_Fuente/Modulos.txt
  docs/index/Español/Código_Fuente/Modulos/Desktop.txt
  docs/index/Español/Código_Fuente/Modulos/Desktop/Config.json.txt
  docs/index/Español/Código_Fuente/Modulos/Server.txt
  docs/index/Español/Código_Fuente/Modulos/Server/Server.json.txt
  docs/index/Español/Código_Fuente/Modulos/Shared.txt
  docs/index/Español/Documentación_externa.txt
  docs/index/Español/Gradlew.txt
  docs/index/Español/Manual_del_jugador.txt
  docs/index/Ingles.txt
  docs/index/Ingles/Development_Enviroment.txt
  docs/index/Ingles/Key_config_to_play.txt
  docs/index/Ingles/Run_on_console.txt
  docs/index/img/client-run.png
  docs/index/img/design-run.png
  docs/index/img/evitar-dos-cambios-en-un-commit.png
  docs/index/img/gradle-project.png
  docs/index/img/pr-to-merge.png
  docs/index/img/pr-to-squash.png
  docs/index/img/resultado-merger.png
  docs/index/img/resultado-squash.png
  docs/index/img/select-java-version.png
  docs/index/img/server-run.png
  docs/notebook.zim
  docs/readme.md
  docs/template-export/Ecodiv-responsive.html
  docs/template-export/Ecodiv-responsive/github.png
  docs/template-export/Ecodiv-responsive/header_1.png
  docs/template-export/Ecodiv-responsive/header_1.svg
  docs/template-export/Ecodiv-responsive/menu.png
  docs/template-export/Ecodiv-responsive/menu.svg
  docs/template-export/Ecodiv-responsive/menu2.svg
  docs/template-export/Ecodiv-responsive/script.js
  docs/template-export/Ecodiv-responsive/style.css
  docs/template-export/Ecodiv-responsive/style1.css
  docs/template-export/Ecodiv-responsive/style2.css
  docs/template-export/Ecodiv-responsive/style3.css
  docs/template-export/Ecodiv-responsive/style4.css
  docs/template-export/Ecodiv-responsive/telegram.png
  docs/template-export/LICENSE.md
  docs/template-export/README.md
Labels: documentation, help wanted

#242 Calculo de daño a distancia - cambio de formula
  client/src/game/managers/AOInputProcessor.java
  client/src/game/ui/Inventory.java
  client/src/game/ui/InventoryQuickBar.java
  client/src/game/ui/SpellView.java
  docs/index/Español/ChangeLog.txt
  server/src/server/systems/combat/AbstractCombatSystem.java
  server/src/server/systems/combat/RangedCombatSystem.java
Labels: enhancement

#252 Added a quick start to run the project
  README.md
Labels: documentation

#256 Actualizamos changeLog
  docs/index/Español/ChangeLog.txt
Labels: documentation, refactor
