Repository ao-libre/finisterra, pull requests merged in 2022-04, with the labels that each got.

#385 Actualización botón agregar servidor + imagen faltante
  client/src/game/screens/LoginScreen.java
  desktop/assets/data/graphics/23669.png
Labels: bug, enhancement

#386 Login Screen updates and fixes [Develop Branch]
  client/src/game/screens/LoginScreen.java
  client/src/game/ui/WidgetFactory.java
  desktop/assets/data/ui/ao-skin-2/ao-skin.atlas
Labels: bug, enhancement

#379 Cambio paths absolutos a relativos
  Accounts/asd.json
  CharFiles/asd.json
  client/Config.json
  client/src/game/utils/Resources.java
  server/src/server/configs/CharConfiguration.java
  server/src/server/configs/ServerConfiguration.java
Labels: bug, WIP

#398 Comando /help #389
  client/src/game/ui/AOConsole.java
  server/src/server/systems/network/CommandSystem.java
Labels: enhancement

#401 Encapsular connectionId dentro de Network
  server/src/server/systems/account/AccountSystem.java
  server/src/server/systems/account/UserSystem.java
  server/src/server/systems/network/ServerRequestProcessor.java
  server/src/server/systems/network/ServerSystem.java
  server/src/server/systems/world/WorldEntitiesSystem.java
  server/src/server/systems/world/entity/item/ItemActionSystem.java
  server/src/server/systems/world/entity/movement/MovementSystem.java
  server/src/server/systems/world/entity/npc/NPCActionSystem.java
  server/src/server/systems/world/entity/user/PlayerActionSystem.java
  shared/src/shared/network/interaction/DropItem.java
Labels: refactor

#410 Se puede Teletransportar por el mapa con Shift + Click.
  client/src/game/systems/actions/PlayerActionSystem.java
  client/src/game/systems/input/InputSystem.java
  components/src/component/position/WorldPos.java
  server/src/server/systems/network/CommandSystem.java
  server/src/server/systems/network/ServerRequestProcessor.java
  server/src/server/systems/world/entity/movement/MovementSystem.java
  server/src/server/systems/world/entity/user/PlayerActionSystem.java
  shared/src/shared/interfaces/FXs.java
  shared/src/shared/network/init/NetworkDictionary.java
  shared/src/shared/network/interaction/TeleportRequest.java
  shared/src/shared/network/interfaces/DefaultRequestProcessor.java
  shared/src/shared/network/interfaces/IRequestProcessor.java
Labels: enhancement
